version: '3.8'
services:
  ptinder:
    # Pull image (by default from Docker Hub)
    image: shapovalovairina/ptinder.server:latest
    # Here you can set environment variables if you want
    # In ENV_HOST pghost - database host (in our case network alias for postgres, see below)
    # ENV_HOST ptinder - database name
    environment:
      - ENV_PASSWORD=123
      - ENV_USER=ptinder
      - ENV_HOST=jdbc:postgresql://pghost/ptinder
    # Expose port 8080. It means port 8080 on host -> port 8080 on container
    ports:
      - 8080:8080
    deploy:
      replicas: 1
    networks:
      - backend_network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=ptinder
      - POSTGRES_DB=ptinder
    ports:
      - 5432:5432
    deploy:
      replicas: 1
    # On container network this container with have alias pghost
    networks:
      backend_network:
        aliases:
          - pghost

# Just network for container communication
networks:
  backend_network:
    driver: overlay
